openapi: 3.0.0
info:
  title: API de ejemplo
  version: "1.0.0"
  description: Documentación mínima de prueba
servers:
  - url: http://localhost:3000
paths:
  /ping:
    get:
      summary: Verifica que el servidor responde
      responses:
        '200':
          description: OK
